name: sinyalist
description: Mission-critical earthquake survival system for Istanbul.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cryptography: ^2.7.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  geolocator: ^13.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
